#!/usr/bin/env node
/* Emit dist/sw.js.
 *
 * The site is entirely static JSON and Markdown, which makes it a good fit for
 * offline use — aspirants read briefings and take quizzes on mobile with patchy
 * data. The worker precaches the app shell and caches content as it is visited.
 *
 * The precache list and cache version are injected at build time so a new
 * deploy always lands in a fresh cache and the old one is dropped.
 */

const fs = require("fs");
const path = require("path");

// Content the app fetches on demand. Served stale-while-revalidate: instant
// from cache, refreshed in the background so a regenerated note still updates.
const CONTENT_PREFIXES = [
  "data/", "daily/", "weekly/", "monthly/", "generated_data/",
  "generated_questions/", "anki/", "reference/", "fodder/", "config/",
];

function serviceWorkerSource({ version, precache, contentCacheLimit = 500 }) {
  return `/* Generated by scripts/generate_service_worker.js — do not edit by hand. */
const VERSION = ${JSON.stringify(version)};
const SHELL_CACHE = \`pariksha-shell-\${VERSION}\`;
const CONTENT_CACHE = "pariksha-content-v1";
const CONTENT_LIMIT = ${contentCacheLimit};
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const CONTENT_PREFIXES = ${JSON.stringify(CONTENT_PREFIXES)};

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    // addAll is atomic: one 404 would leave the whole shell uncached, so each
    // entry is added individually and a missing one is simply skipped.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const response = await fetch(url, { cache: "reload" });
        if (response.ok) await cache.put(url, response);
      } catch (error) {
        /* offline at install time; the runtime handler will fill this in */
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.map((name) => {
      if (name.startsWith("pariksha-shell-") && name !== SHELL_CACHE) return caches.delete(name);
      return null;
    }));
    await self.clients.claim();
  })());
});

// Keep the content cache from growing without limit over a year of daily notes.
async function trimContentCache(cache) {
  const keys = await cache.keys();
  if (keys.length <= CONTENT_LIMIT) return;
  // Oldest insertions first — Cache.keys() preserves insertion order.
  await Promise.all(keys.slice(0, keys.length - CONTENT_LIMIT).map((key) => cache.delete(key)));
}

function isContentRequest(url) {
  if (url.pathname.endsWith(".md")) return true;
  const relative = url.pathname.replace(/^\\//, "");
  return CONTENT_PREFIXES.some((prefix) => relative.startsWith(prefix));
}

// Which cache a URL belongs in. The fetch handler and the explicit
// "save for offline" path must agree, or a saved file would be written to one
// cache and looked up in the other.
function cacheNameFor(url) {
  if (url.searchParams.has("v")) return SHELL_CACHE;
  if (url.pathname.replace(/^\\//, "").startsWith("vendor/")) return SHELL_CACHE;
  return CONTENT_CACHE;
}

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response.ok) await cache.put(request, response.clone());
  return response;
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CONTENT_CACHE);
  const hit = await cache.match(request);
  const network = fetch(request).then(async (response) => {
    if (response.ok) {
      await cache.put(request, response.clone());
      await trimContentCache(cache);
    }
    return response;
  }).catch(() => null);
  if (hit) return hit;
  const response = await network;
  if (response) return response;
  return new Response("Offline and not cached.", { status: 504, statusText: "Offline" });
}

// Navigations go to the network first so a new deploy is picked up promptly,
// falling back to the cached shell when there is no connection.
async function navigationHandler(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(SHELL_CACHE);
      await cache.put("index.html", response.clone());
    }
    return response;
  } catch (error) {
    const cache = await caches.open(SHELL_CACHE);
    return (await cache.match("index.html")) || Response.error();
  }
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(navigationHandler(request));
    return;
  }
  // Content-hashed assets never change under the same URL.
  if (url.searchParams.has("v")) {
    event.respondWith(cacheFirst(request, SHELL_CACHE));
    return;
  }
  if (url.pathname.replace(/^\\//, "").startsWith("vendor/")) {
    event.respondWith(cacheFirst(request, SHELL_CACHE));
    return;
  }
  if (isContentRequest(url)) {
    event.respondWith(staleWhileRevalidate(request));
    return;
  }
});

// Lets the app ask for a batch of notes to be stored for offline reading.
self.addEventListener("message", (event) => {
  const data = event.data || {};
  if (data.type !== "cache-urls" || !Array.isArray(data.urls)) return;
  event.waitUntil((async () => {
    const contentCache = await caches.open(CONTENT_CACHE);
    for (const url of data.urls.slice(0, 400)) {
      try {
        const cache = await caches.open(cacheNameFor(new URL(url, self.location.origin)));
        if (await cache.match(url)) continue;
        const response = await fetch(url);
        if (response.ok) await cache.put(url, response);
      } catch (error) {
        /* skip anything unreachable */
      }
    }
    await trimContentCache(contentCache);
    const clients = await self.clients.matchAll();
    for (const client of clients) client.postMessage({ type: "cache-urls-done" });
  })());
});
`;
}

function writeServiceWorker(distDir, options) {
  const outPath = path.join(distDir, "sw.js");
  const source = serviceWorkerSource(options);
  fs.writeFileSync(outPath, source, "utf8");
  return { bytes: Buffer.byteLength(source), precached: options.precache.length };
}

module.exports = { writeServiceWorker, serviceWorkerSource };
